module.exports = {
  BASE_URL: 'https://api.pdffiller.com',
  AUTH_ENDPOINT: '/v2/oauth/token',
  TEMPLATES_ENDPOINT: '/v2/templates',
  TEMPLATES_BY_ID_ENDPOINT: '/v2/templates/{template_id}',
  TEMPLATES_DOWNLOAD_ENDPOINT: '/v2/templates/{template_id}/download',
  TEMPLATES_DOWNLOAD_ORIGINAL_ENDPOINT: '/v2/templates/{template_id}/original_document',
  TEMPLATES_ROLES_ENDPOINT: '/v2/templates/{template_id}/roles',
  TEMPLATES_FIELDS_ENDPOINT: '/v2/templates/{template_id}/fields',
  TEMPLATES_FILLED_DOCS_ENDPOINT: '/v2/templates/{template_id}/filled_documents',
  TEMPLATES_DOWNLOAD_SIGNATURES_ENDPOINT: '/v2/templates/{template_id}/download_signatures',
  TEMPLATES_CONSTRUCTOR_ENDPOINT: '/v2/templates/{template_id}/constructor',
  APPLICATIONS_ENDPOINT: '/v2/applications',
  APPLICATIONS_BY_ID_ENDPOINT: '/v2/applications/{application_id}',
  APPLICATIONS_USERS_BY_ID_ENDPOINT: '/v2/applications/{application_id}/users',
  CALLBACKS_ENDPOINT: '/v2/callbacks',
  CALLBACKS_BY_ID_ENDPOINT: '/v2/callbacks/{callback_id}',
  CALLBACKS_GLOBAL_BY_ID_ENDPOINT: '/v2/callbacks/global',
  FOLDERS_ENDPOINT: '/v2/folders',
  FOLDERS_BY_ID_ENDPOINT: '/v2/folders/{folder_id}',
  TOKENS_ENDPOINT: '/v2/tokens',
  TOKENS_BY_ID_ENDPOINT: '/v2/tokens/{token_id}',
  CUSTOM_LOGOS_ENDPOINT: '/v2/custom_branding/custom_logo',
  CUSTOM_LOGOS_BY_ID_ENDPOINT: '/v2/custom_branding/custom_logo/{custom_logo_id}',
  USERS_ENDPOINT: '/v2/users/me',
};

